### ISSUE TITLE
'Next Up' widget error upon startup

### ISSUE THREAD

**Issue by ksandersbna** [realcopacetic/script.copacetic.helper#7]
I am encountering an issue with Copacetic Helper where it fails to load the 'Next Up' widget. I did confirm the widget continues to work in other skins. The error says, 'Check the logs for more details'. In review of the logs, I have the following error:

2024-05-03 09:39:22.224 T:15232 error : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "C:\Users\ksand\AppData\Roaming\Kodi\addons\script.copacetic.helper\plugin.py", line 6, in
Main()
File "C:\Users\ksand\AppData\Roaming\Kodi\addons\script.copacetic.helper\resources\lib\plugin\main.py", line 18, in init
self.getinfos()
File "C:\Users\ksand\AppData\Roaming\Kodi\addons\script.copacetic.helper\resources\lib\plugin\main.py", line 45, in getinfos
self._execute(plugin, self.info)
File "C:\Users\ksand\AppData\Roaming\Kodi\addons\script.copacetic.helper\resources\lib\plugin\main.py", line 54, in _execute
getattr(plugin, action.lower())()
File "C:\Users\ksand\AppData\Roaming\Kodi\addons\script.copacetic.helper\resources\lib\plugin\content.py", line 183, in next_up
episode_details[0]['studio'] = studio
IndexError: list index out of range
-->End of Python script error report<--

**Comment by ksandersbna** [comment]
Closing ticket. I had failed to add the repo to Kodi. I added the repo and copacetic helper updated to the latest. Confirmed that there are no further errors and able to see all my episodes in the 'Next Up' widget.
